---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: box-cutter/ubuntu1404
  - name: centos-7.1
    driver:
      box: box-cutter/centos71
  - name: centos-6.7
    driver:
      box: box-cutter/centos67

suites:
  - name: default
    run_list: chef_solo_proxy::default
    attributes:
      chef_solo_proxy:
        # replace with valid choices for your network.
        # if invalid, verify will fail to download busser
        # Alternativly, test using the "disable" suite
        https_proxy: http://192.168.0.3:3128
        http_proxy: http://192.168.0.3:3128
        no_proxy:
          - 127.0.0.1
          - 192.168.1.1
          - '*.com'
          - '*.org'
  - name: disable
    run_list: chef_solo_proxy::default
    attributes:
      chef_solo_proxy:
        https_proxy:
        http_proxy:
        no_proxy:
