---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  attributes:
    java:
      ark_retries: 2
      ark_retry_delay: 10
  roles_path: provision/chef/roles
  data_bags_path:  provision/chef/data_bags
  cookbook_path:
    - ./
    - provision/chef/cookbooks
    - provision/chef/vendor-cookbooks

platforms:
  - name: ubuntu-14.04
    driver:
      box: box-cutter/ubuntu1404
#  - name: centos-7.1
#    driver:
#      box: box-cutter/centos71
  - name: centos-6.7
    driver:
      box: box-cutter/centos67

suites:
  - name: default
    run_list: chef_solo_proxy::default
    attributes:
      chef_solo_proxy:
        https_proxy: https://test.com
        http_proxy: http://test.com
        no_proxy:
          - 127.0.0.1
          - 192.168.1.1
          - '*.com'
          - '*.org'
  - name: disable_proxy
    run_list: chef_solo_proxy::default
    attributes:
      chef_solo_proxy:
        https_proxy:
        http_proxy:
        no_proxy:
