language: ruby
cache: bundler
gemfile:
  - test/support/Gemfile
bundler_args: --jobs 7 --retry 3
script: bundle exec rake default
rvm:
  - 1.9.3
  - 2.1.8
  - 2.2.4
branches:
  only:
    - master
    - develop
