source 'https://rubygems.org'

gem 'rake', '10.4.2'
gem 'chef', '12.4.3'
gem 'chefspec', '4.5.0'
gem 'foodcritic', '5.0.0'
gem 'rubocop'
gem 'test-kitchen'

group :development do
  gem "knife-spork", '1.6.1'
  gem "berkshelf", '4.0.1'
end
